# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QPackage_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QPackageDialogBase(object):
    def setupUi(self, QPackageDialogBase):
        QPackageDialogBase.setObjectName("QPackageDialogBase")
        QPackageDialogBase.resize(492, 591)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(QPackageDialogBase)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self._charger = QtWidgets.QPushButton(QPackageDialogBase)
        self._charger.setObjectName("_charger")
        self.horizontalLayout_3.addWidget(self._charger)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self._tableau = QtWidgets.QTableView(QPackageDialogBase)
        self._tableau.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self._tableau.setAlternatingRowColors(True)
        self._tableau.setSortingEnabled(True)
        self._tableau.setObjectName("_tableau")
        self._tableau.horizontalHeader().setDefaultSectionSize(1000)
        self.verticalLayout.addWidget(self._tableau)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._repertoire = QtWidgets.QLineEdit(QPackageDialogBase)
        self._repertoire.setObjectName("_repertoire")
        self.horizontalLayout.addWidget(self._repertoire)
        self._repertoire_boutton = QtWidgets.QPushButton(QPackageDialogBase)
        self._repertoire_boutton.setObjectName("_repertoire_boutton")
        self.horizontalLayout.addWidget(self._repertoire_boutton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(QPackageDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self._projectname = QtWidgets.QLineEdit(QPackageDialogBase)
        self._projectname.setText("")
        self._projectname.setObjectName("_projectname")
        self.horizontalLayout_5.addWidget(self._projectname)
        self.label_3 = QtWidgets.QLabel(QPackageDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(QPackageDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self._listeprojections = QtWidgets.QComboBox(QPackageDialogBase)
        self._listeprojections.setEditable(True)
        self._listeprojections.setObjectName("_listeprojections")
        self.horizontalLayout_2.addWidget(self._listeprojections)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self._copy = QtWidgets.QPushButton(QPackageDialogBase)
        self._copy.setObjectName("_copy")
        self.horizontalLayout_4.addWidget(self._copy)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self._progression = QtWidgets.QProgressBar(QPackageDialogBase)
        self._progression.setProperty("value", 0)
        self._progression.setObjectName("_progression")
        self.verticalLayout.addWidget(self._progression)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(QPackageDialogBase)
        self._repertoire_boutton.clicked.connect(QPackageDialogBase.chercherRepertoire)
        self._charger.clicked.connect(QPackageDialogBase.chargerCouches)
        self._copy.clicked.connect(QPackageDialogBase.copierCouches)
        QtCore.QMetaObject.connectSlotsByName(QPackageDialogBase)

    def retranslateUi(self, QPackageDialogBase):
        _translate = QtCore.QCoreApplication.translate
        QPackageDialogBase.setWindowTitle(_translate("QPackageDialogBase", "QPackage"))
        self._charger.setText(_translate("QPackageDialogBase", "Load layers of the current project"))
        self._repertoire_boutton.setText(_translate("QPackageDialogBase", "Destination folder"))
        self.label_2.setText(_translate("QPackageDialogBase", "Project name : "))
        self.label_3.setText(_translate("QPackageDialogBase", "(.qgs)"))
        self.label.setText(_translate("QPackageDialogBase", "Choose the CRS : "))
        self._copy.setText(_translate("QPackageDialogBase", "Copy the layers"))

